"""add oauth_profile_pic to users

Revision ID: 9fa80b1b728e
Revises: a3f9e1c7b2d4
Create Date: 2026-08-19 02:14:08.649793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa80b1b728e'
down_revision = 'a3f9e1c7b2d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('level_discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_profile_pic', sa.String(length=500), nullable=True))
        batch_op.alter_column('loyalty_points',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('loyalty_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'bronze'"))
        batch_op.alter_column('total_spent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('total_spent',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('loyalty_level',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'bronze'"))
        batch_op.alter_column('loyalty_points',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
        batch_op.drop_column('oauth_profile_pic')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('level_discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
