"""add tracking and admin notes to orders

Revision ID: c20bcaa01825
Revises: d9952823a080
Create Date: 2026-08-02 19:14:00.229794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20bcaa01825'
down_revision = 'd9952823a080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('admin_notes')

    # ### end Alembic commands ###
