"""add loyalty system

Revision ID: e0686771e09d
Revises: 36291e876c7b
Create Date: 2026-08-03 14:37:14.845563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0686771e09d'
down_revision = '36291e876c7b'
branch_labels = None
depends_on = None


def upgrade():
    # Verificar si la tabla ya existe antes de crearla
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'loyalty_transactions' not in tables:
        op.create_table('loyalty_transactions',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('points', sa.Integer(), nullable=False),
            sa.Column('reason', sa.String(length=200), nullable=False),
            sa.Column('order_id', sa.Integer(), nullable=True),
            sa.Column('balance_after', sa.Integer(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(['order_id'], ['orders.id']),
            sa.ForeignKeyConstraint(['user_id'], ['users.id']),
            sa.PrimaryKeyConstraint('id')
        )
    
    # Agregar campos a users (con verificación)
    columns = [col['name'] for col in inspector.get_columns('users')]
    if 'loyalty_points' not in columns:
        op.add_column('users', sa.Column('loyalty_points', sa.Integer(), nullable=True, server_default='0'))
    if 'loyalty_level' not in columns:
        op.add_column('users', sa.Column('loyalty_level', sa.String(length=20), nullable=True, server_default='bronze'))
    if 'total_spent' not in columns:
        op.add_column('users', sa.Column('total_spent', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'))
    
    # Agregar campo a orders
    order_columns = [col['name'] for col in inspector.get_columns('orders')]
    if 'level_discount' not in order_columns:
        op.add_column('orders', sa.Column('level_discount', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0'))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('total_spent')
        batch_op.drop_column('loyalty_level')
        batch_op.drop_column('loyalty_points')

    op.drop_table('loyalty_transactions')
    # ### end Alembic commands ###
