"""add customer and shipping details to orders

Revision ID: f7136be5902b
Revises: b2a0717455c4
Create Date: 2026-08-02 00:44:30.843578

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'f7136be5902b'
down_revision = 'b2a0717455c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.drop_column('street')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('product_sku', sa.String(length=50), nullable=False))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_email', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('shipping_city', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('shipping_state', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('shipping_zip', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('shipping_country', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('shipping_address',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('shipping_address',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('notes')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_id')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('shipping_cost')
        batch_op.drop_column('subtotal')
        batch_op.drop_column('shipping_country')
        batch_op.drop_column('shipping_zip')
        batch_op.drop_column('shipping_state')
        batch_op.drop_column('shipping_city')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('customer_email')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('product_sku')
        batch_op.drop_column('product_name')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_default')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('address')
        batch_op.drop_column('phone')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
